### ISSUE TITLE
Drop down menu doesn't work in Firefox 34 and newer

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedMain#6]
Drop down menu doesn't work in Firefox 34 and newer, this issue is easily solvable if we just removed the opacity: 0.9; line in header from the style.css file.

But then we looses the transparancy that is supposed to be there.

**Comment by halvors** [comment]
This was temporary fixed by removing the "opacity" from the dropdown menu.

**Comment by petterroea** [comment]
Luckily a new design is in the roadmap

**Comment by halvors** [comment]
Closing this.
